name: test

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: cachix/install-nix-action@v31
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: download gleam dependencies
        shell: 'nix develop -c bash -e {0}'
        run: gleam deps download
      - name: gleam test on erlang target
        shell: 'nix develop -c bash -e {0}'
        run: gleam test
      - name: gleam test on nodejs target
        shell: 'nix develop -c bash -e {0}'
        run: gleam test -t javascript
      - name: gleam check formatting
        shell: 'nix develop -c bash -e {0}'
        run: gleam format --check src test
